font_size           13
font_family         FiraCode Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto
background_opacity  1 


# BEGIN_KITTY_THEME
# Aquarium Dark
include ~/.cache/wal/colors-kitty.conf
# END_KITTY_THEME
