# Shell variables
# Generated by 'wal'
wallpaper='/home/akshat/Wallpaper.png'

# Special
background='#0a0a11'
foreground='#c0d0e0'
cursor='#c0d0e0'

# Colors
color0='#0a0a11'
color1='#444659'
color2='#525569'
color3='#60647A'
color4='#6D738A'
color5='#7988A1'
color6='#8895AF'
color7='#c0d0e0'
color8='#86919c'
color9='#444659'
color10='#525569'
color11='#60647A'
color12='#6D738A'
color13='#7988A1'
color14='#8895AF'
color15='#c0d0e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
