--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/akshat/Wallpaper.png"

-- Special
background="#0a0a11"
foreground="#c0d0e0"
cursor="#c0d0e0"

-- Colors
color0="#0a0a11"
color1="#444659"
color2="#525569"
color3="#60647A"
color4="#6D738A"
color5="#7988A1"
color6="#8895AF"
color7="#c0d0e0"
color8="#86919c"
color9="#444659"
color10="#525569"
color11="#60647A"
color12="#6D738A"
color13="#7988A1"
color14="#8895AF"
color15="#c0d0e0"
